### PR TITLE
now raising an exception with value error

### PR DESCRIPTION
**Pull request by ashvindersingh**
One liner but important change.

### CODE REVIEW

**Comment by sethrosetter** [comment]
@ashvindersingh Can you kick of the functional tests targeting this branch and we can merge when the results come back?

**Comment by ashvindersingh** [comment]
Yeah good point! In this particular case one test using the parallel function should validate the change. Going forward we should continue with this practice.

**Comment by sethrosetter** [comment]
@ashvindersingh I completely agree.

**Comment by sethrosetter** [comment]
@ashvindersingh Did you test this out / am I able to merge this?

**Pull request merged**
