### PR TITLE
Add ability to build with -race flag (or any other build flags)

### PR DESCRIPTION
**Pull request by tleyden**

### CODE REVIEW

**Comment by tleyden** [comment]
Needed for https://github.com/couchbase/sync_gateway/issues/1400

**Comment by sethrosetter** [comment]
@tleyden does this affect existing behavior in anyway if no flags are supplied?

**Comment by tleyden** [comment]
It shouldn't, because it will just be passing an empty string to `build.sh` as an argument

**Comment by sethrosetter** [comment]
@tleyden this crashes when no build flags are specified due to passing None

**Comment by tleyden** [comment]
Ok great catch!  We just need a way to convert None to an empty string .. unless you have a cleaner way in mind.

**Comment by sethrosetter** [comment]
@tleyden That should work

**Comment by tleyden** [comment]
@sethrosetter can you take a look?

**Pull request merged**
