### PR TITLE
http request retry mechanism

### PR DESCRIPTION
**Pull request by ashvindersingh**
This PR implements: 
- HTTP requests retry logic
- Parameterization of single_user_single_channel_doc_updates

### CODE REVIEW

**Comment by tleyden** [comment]
I think this PR needs more cleanup, if you just squash those two commits into a single commit and do a force push, that should do it.

**Comment by sethrosetter** [comment]
Should we implement this for all the requests or no?

**Comment by ashvindersingh** [comment]
@sethrosetter By default the retry mechanism is for both adding and updating docs.

**Comment by sethrosetter** [comment]
@ashvindersingh Do we want retry on bulk_docs or no?

**Comment by ashvindersingh** [comment]
@sethrosetter I think we should do

**Pull request merged**
