### PR TITLE
Fixes #198 by adding a validate_cluster method

### LINKED ISSUE #198: Validate cluster setup before running functional test
Currently to work properly, the functional tests require:

- exactly 3 SG’s  (less will cause failures, more will be ignored)
- at least one is an index reader

add a validation step as part of the cluster.reset() phase, and:

- if less than 3 SG's fail with a clear error
- if more than 3 SG's print a warning that the rest will be ignored
- if no index readers, then fail with a clear error

### PR DESCRIPTION
**Pull request by tleyden**
https://github.com/couchbaselabs/sync-gateway-testcluster/issues/198

### CODE REVIEW

**Comment by tleyden** [comment]
Sample output when running with provisioning_config with no index readers defined:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self =

Sync Gateways
SyncGateway: sg1:ec2-54-161-145-152.compute-1.amazonaws.com
SyncGateway: sg2:ec2-54-158-99-77.compute-...45-134-37.compute-1.amazonaws.com

Load Generators
{'ip': 'ec2-54-161-219-195.compute-1.amazonaws.com', 'name': 'lg1'}


    def validate_cluster(self):

        # Validate sync gateways
        if len(self.sync_gateways) < 3:
            raise Exception("Functional tests require at least 3 sync gateways")

        if len(self.sync_gateways) > 3:
            print("WARNING: more than 3 sync gateways present, only first 3 will be used")

        num_index_readers = len(self.sync_gateways) - len(self.sync_gateway_writers)
        if num_index_readers == 0:
>           raise Exception("Functional tests require at least 1 index reader")
E           Exception: Functional tests require at least 1 index reader

lib/cluster.py:60: Exception
=============================================================== 1 failed in 16.42 seconds ================================================================
```

**Comment by sethrosetter** [comment]
This has the potential to blow up on 1IR / 1IW performance test scenarios where we only have 2 sync_gateways

**Comment by tleyden** [comment]
Ok, what about just doing this check?

```
num_index_readers = len(self.sync_gateways) - len(self.sync_gateway_writers)
         if num_index_readers == 0:
             raise Exception("Functional tests require at least 1 index reader")
```

**Comment by sethrosetter** [comment]
@tleyden that looks good to me

**Comment by tleyden** [comment]
OK I repushed with that change.

**Comment by sethrosetter** [comment]
@tleyden thanks!

**Pull request merged**
