### PR TITLE
Add code to run zipgrep and check for races, panics

### PR DESCRIPTION
**Pull request by tleyden**
Related to https://github.com/couchbase/sync_gateway/issues/1400

### CODE REVIEW

**Comment by tleyden** [comment]
@sethrosetter this should be ready to merge.

Successful run: http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-RACES/14/console

**Comment by sethrosetter** [comment]
@tleyden Can you include the ansible ignore failures provisioning changes you made for the fetch logs playbook?

**Comment by tleyden** [comment]
Here is a test run with the same params on the master branch of sync-gateway-test-cluster

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-RACES/15/console

which also contains these errors:

```
TASK: [Fetch sg_accel logs] *************************************************** 
failed: [sg1] => {"failed": true, "file": "/home/sg_accel/logs/sg_accel_error.log"}
msg: the remote file does not exist
failed: [sg2] => {"failed": true, "file": "/home/sg_accel/logs/sg_accel_error.log"}
msg: the remote file does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/fetch-sync-gateway-logs.retry

sg1                        : ok=2    changed=0    unreachable=0    failed=1   
sg2                        : ok=2    changed=0    unreachable=0    failed=1   
sg3                        : ok=2    changed=1    unreachable=0    failed=0   

2016-01-25 17:44:22,844 - ERROR - fetch_sync_gateway_logs - Error pulling logs

```

**Comment by tleyden** [comment]
> Can you include the ansible ignore failures provisioning changes you made for the fetch logs playbook?

I didn't change anything in ansible .. I think those log collection errors aren't related to this change, we should tackle that in a separate PR.

**Comment by sethrosetter** [comment]
Cool. One last thing. Do we need to document the install of zipgrep as a dependency anywhere?

**Comment by sethrosetter** [comment]
@tleyden Love this. Thanks!

**Comment by tleyden** [comment]
> Do we need to document the install of zipgrep as a dependency anywhere?

Added to the Dockerfile:

https://github.com/couchbaselabs/sync-gateway-testcluster/commit/29e821c9c3f66af7dc56ad3ffa886f44fb168104

**Pull request merged**
