### PR TITLE
Create cbgt-bucket at startup

### PR DESCRIPTION
**Pull request by tleyden**
It seems a bit strange to create 2 buckets and then have them later re-created with 3 buckets.

### CODE REVIEW

**Comment by sethrosetter** [comment]
@tleyden Can you update here as well https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/provision/ansible/playbooks/install-sync-gateway-package.yml#L30

**Comment by tleyden** [comment]
Here's the problem it solves: https://github.com/couchbaselabs/sync-gateway-testcluster/issues/60

**Comment by tleyden** [comment]
@sethrosetter done

**Comment by sethrosetter** [comment]
looks good to me

**Pull request merged**
