### PR TITLE
Feature/ansible 2.0 upgrade

### PR DESCRIPTION
**Pull request by sethrosetter**
! IMPORTANT - After merge, the provisioning is not guaranteed to work with pre 2.0 ansible so make sure you do the following
```
pip uninstall ansible
pip install ansible
```

Also, @adamcfraser and @tleyden, heads up ^

Provisioning now supports ansible 2.0
- changed sudo: True -> become: yes (sudo is being deprecated)
- ansible_ssh_host -> ansible_host
- minor provisioning clean up 
    - used file module to remove in as many places as I could
- minor API changes when using Ansible python API

### CODE REVIEW

**Comment by tleyden** [comment]
Can you kick off a jenkins run against this branch before merging?

**Comment by sethrosetter** [comment]
@tleyden good call. There is one running right now

**Comment by tleyden** [comment]
Can you post a link?

**Comment by sethrosetter** [comment]
http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests/

**Comment by sethrosetter** [comment]
Clean run - http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests/127/consoleFull. @tleyden Can you take a look at this PR?

**Comment by tleyden** [comment]
I tested on aws and getting:


```
fatal: [sg2]: FAILED! => {"changed": false, "cmd": "/sbin/useradd -m sync_gateway", "failed": true, "msg": "[Errno 13] Permission denied", "rc": 13}

```

Full logs: https://gist.github.com/tleyden/af8c15f63933371e8be7#file-gistfile1-txt-L544

**Comment by sethrosetter** [comment]
@tleyden Looks like I forgot to test the source install for the final changes. I was mostly testing the the package code path. I need to add "becomes" for these two steps https://github.com/couchbaselabs/sync-gateway-testcluster/blob/feature/ansible-2.0-upgrade/provision/ansible/playbooks/install-sync-gateway-source.yml#L35-L46

**Comment by tleyden** [comment]
Now it's failing to build the sync gw:

https://gist.github.com/tleyden/f5e1119211602f6fd067#file-gistfile1-txt-L442-L444

I'm pretty sure that's due to changes in the way we are structuring the repo

**Comment by tleyden** [comment]
I'm re-running with `python provision/provision_cluster.py --server-version=4.1.0 --sync-gateway-branch=1.2.0`

and getting:

```
TASK [Creates /opt/couchbase-sync-gateway] *************************************
fatal: [sg2]: FAILED! => {"changed": false, "failed": true, "msg": "There was an issue creating /opt/couchbase-sync-gateway as requested: 'module' object has no attribute 'EEXISTS'", "path": "/opt/couchbase-sync-gateway", "state": "absent"}
fatal: [sg1]: FAILED! => {"changed": false, "failed": true, "msg": "There was an issue creating /opt/couchbase-sync-gateway as requested: 'module' object has no attribute 'EEXISTS'", "path": "/opt/couchbase-sync-gateway", "state": "absent"}

PLAY RECAP *********************************************************************
```

**Comment by tleyden** [comment]
Deploying via `python provision/provision_cluster.py --server-version=4.1.0 --skip-bucketflush true --sync-gateway-version=1.2.0-79` worked.

**Pull request merged**
